### ISSUE TITLE
关于gaodun_downlaod的issue

### ISSUE THREAD

**Issue by jiangph1001** [arandintday/myblogsource#4]
您好，我是gaodun_download的原作者  
我看到你fork后的项目提到了个别har文件无法提取key值的情况，可否提供一下呢，我的邮箱是jiangph1001@qq.com
因为你的项目没有开启issue功能，我只能在这里提issue了

**Comment by arandintday** [comment]
抱歉fork的时候忘了开issue了，相关文件已发到您的邮箱
